version: '3.8'

services:
  api-gateway:
    image: rajat7121/toprisebackend-api-gateway:latest
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - DOMAIN=toprise.in

  user-service:
    image: rajat7121/toprisebackend-user-service:latest
    volumes:
      - ./services/user-service:/app
      - ./packages:/packages
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - DOMAIN=toprise.in

  product-service:
    image: rajat7121/toprisebackend-product-service:latest
    volumes:
      - ./services/product-service:/app
      - ./packages:/packages
    ports:
      - "5002:5001"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - DOMAIN=toprise.in

  order-service:
    image: rajat7121/toprisebackend-order-service:latest
    volumes:
      - ./services/order-service:/app
      - ./packages:/packages
    ports:
      - "5003:5001"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - DOMAIN=toprise.in
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  notification-service:
    image: rajat7121/toprisebackend-notification-service:latest
    volumes:
      - ./services/notification-service:/app
      - ./packages:/packages
    ports:
      - "5004:5001"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - DOMAIN=toprise.in

  dealer-worker:
    image: rajat7121/toprisebackend-order-service:latest
    volumes:
      - ./services/order-service:/app
      - ./packages:/packages
    working_dir: /app
    command: ["node", "src/jobs/dealerAssignmentWorker.js"]
    depends_on:
      - order-service
      - redis
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - DOMAIN=toprise.in
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PRODUCT_SERVICE_URL=http://product-service:5001
      - MONGODB_URI=mongodb+srv://techdev:H1E0bf2fvvPiKZ36@toprise-staging.nshaxai.mongodb.net/?retryWrites=true&w=majority&appName=Toprise-Staging

  stock-sweeper:
    image: rajat7121/toprisebackend-product-service:latest
    volumes:
      - ./services/product-service:/app
      - ./packages:/packages
    working_dir: /app
    command: ["node", "src/jobs/stockSweeper.js"]
    restart: always
    depends_on: [product-service]
    networks: [app-network]
    environment:
      - NODE_ENV=production
      - DOMAIN=toprise.in

  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volumes/cache:/data
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network
      - elastic

  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.13.4
    restart: always
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch_container:9200"
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - app-network
      - elastic

networks:
  elastic:
    driver: bridge
  app-network:
    driver: bridge
